//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_ContactItemTypeModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AM_ContactItemTypeModel()
        {
            this.AM_TransactionModel = new HashSet<AM_TransactionModel>();
        }
    
        public string ContactItemTypeCode { get; set; }
        public string ContactItemTypeName { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AM_TransactionModel> AM_TransactionModel { get; set; }
    }
}
