//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_DebtModel
    {
        public int DebtId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> TimeOfDebt { get; set; }
        public Nullable<decimal> RemainingAmountAccrued { get; set; }
        public Nullable<int> ImportId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ReturnMasterId { get; set; }
        public Nullable<int> OrderReturnId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string TransactionTypeCode { get; set; }
    }
}
