//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AY_SMSCalendar
    {
        public int ID { get; set; }
        public string SMSContent { get; set; }
        public string SMSTo { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> isSent { get; set; }
        public Nullable<int> NumberOfFailed { get; set; }
    }
}
