//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PeriodModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRM_PeriodModel()
        {
            this.CRM_RemiderModel = new HashSet<CRM_RemiderModel>();
        }
    
        public string PeriodCode { get; set; }
        public string PeriodName { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<int> OrderIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_RemiderModel> CRM_RemiderModel { get; set; }
    }
}
