//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_SMSParameterModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRM_SMSParameterModel()
        {
            this.CRM_Remider_SMSParameter_Mapping = new HashSet<CRM_Remider_SMSParameter_Mapping>();
        }
    
        public int SMSParameterId { get; set; }
        public Nullable<int> SMSTemplateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_Remider_SMSParameter_Mapping> CRM_Remider_SMSParameter_Mapping { get; set; }
        public virtual CRM_SMSTemplateModel CRM_SMSTemplateModel { get; set; }
    }
}
