//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Remider_SMSParameter_Mapping
    {
        public int RemiderId { get; set; }
        public int SMSTemplateId { get; set; }
        public int SMSParameterId { get; set; }
        public string ValueType { get; set; }
        public string Value { get; set; }
    
        public virtual CRM_RemiderModel CRM_RemiderModel { get; set; }
        public virtual CRM_SMSParameterModel CRM_SMSParameterModel { get; set; }
        public virtual CRM_SMSTemplateModel CRM_SMSTemplateModel { get; set; }
    }
}
