//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerModel()
        {
            this.AccountModel = new HashSet<AccountModel>();
            this.Daily_ChicCut_OrderModel = new HashSet<Daily_ChicCut_OrderModel>();
            this.OrderMasterModel = new HashSet<OrderMasterModel>();
            this.PreOrderMasterModel = new HashSet<PreOrderMasterModel>();
            this.TreatmentModel = new HashSet<TreatmentModel>();
        }
    
        public int CustomerId { get; set; }
        public Nullable<int> CustomerLevelId { get; set; }
        public string FullName { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string EnterpriseName { get; set; }
        public string TaxCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string ImageUrl { get; set; }
        public string Note { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> AdditionalPurchase { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountModel> AccountModel { get; set; }
        public virtual CustomerLevelModel CustomerLevelModel { get; set; }
        public virtual DistrictModel DistrictModel { get; set; }
        public virtual ProvinceModel ProvinceModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_ChicCut_OrderModel> Daily_ChicCut_OrderModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMasterModel> OrderMasterModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreOrderMasterModel> PreOrderMasterModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentModel> TreatmentModel { get; set; }
    }
}
