//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_ChicCut_Pre_OrderModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Daily_ChicCut_Pre_OrderModel()
        {
            this.Daily_ChicCut_Pre_OrderDetailModel = new HashSet<Daily_ChicCut_Pre_OrderDetailModel>();
        }
    
        public int PreOrderId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string FullName { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<int> HairTypeId { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<int> BillDiscountTypeId { get; set; }
        public Nullable<decimal> BillDiscount { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
        public Nullable<int> CanceledUserId { get; set; }
        public Nullable<decimal> SumCOGSOfOrderDetail { get; set; }
        public Nullable<decimal> MinSumPriceOfOrderDetail { get; set; }
        public Nullable<decimal> MaxSumPriceOfOrderDetail { get; set; }
        public Nullable<decimal> MinTotalBillDiscount { get; set; }
        public Nullable<decimal> MaxTotalBillDiscount { get; set; }
        public Nullable<decimal> MinTotal { get; set; }
        public Nullable<decimal> MaxTotal { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> AppointmentTime { get; set; }
        public string PreOrderCode { get; set; }
        public string ServicesName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_ChicCut_Pre_OrderDetailModel> Daily_ChicCut_Pre_OrderDetailModel { get; set; }
    }
}
