//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_ChicCut_OrderDetailModel
    {
        public int OrderDetailId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> TreatmentId { get; set; }
        public Nullable<decimal> COGS { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> UnitCOGS { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> QuantificationMasterId { get; set; }
    
        public virtual Daily_ChicCut_OrderModel Daily_ChicCut_OrderModel { get; set; }
        public virtual Master_ChicCut_ServiceModel Master_ChicCut_ServiceModel { get; set; }
    }
}
