//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_ChicCut_OrderStatusModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Daily_ChicCut_OrderStatusModel()
        {
            this.Daily_ChicCut_OrderModel = new HashSet<Daily_ChicCut_OrderModel>();
        }
    
        public int OrderStatusId { get; set; }
        public string StatusName { get; set; }
        public string Description { get; set; }
        public string StatusNameForSMS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_ChicCut_OrderModel> Daily_ChicCut_OrderModel { get; set; }
    }
}
