//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRateModel
    {
        public int ExchangeRateId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
    
        public virtual CurrencyModel CurrencyModel { get; set; }
    }
}
