//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEOtherMasterModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IEOtherMasterModel()
        {
            this.IEOtherDetailModel = new HashSet<IEOtherDetailModel>();
        }
    
        public int IEOtherMasterId { get; set; }
        public string IEOtherMasterCode { get; set; }
        public int WarehouseId { get; set; }
        public int InventoryTypeId { get; set; }
        public string CustomerName { get; set; }
        public string Phone { get; set; }
        public string SenderName { get; set; }
        public string ReceiverName { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedAccount { get; set; }
        public Nullable<int> CreatedEmployeeId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedAccount { get; set; }
        public Nullable<int> DeletedEmployeeId { get; set; }
        public bool Actived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEOtherDetailModel> IEOtherDetailModel { get; set; }
        public virtual InventoryTypeModel InventoryTypeModel { get; set; }
        public virtual WarehouseModel WarehouseModel { get; set; }
    }
}
