//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_ChicCut_QuantificationDetailModel
    {
        public int QuantificationDetailId { get; set; }
        public Nullable<int> QuantificationMasterId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Qty { get; set; }
    
        public virtual Master_ChicCut_QuantificationMasterModel Master_ChicCut_QuantificationMasterModel { get; set; }
        public virtual ProductModel ProductModel { get; set; }
    }
}
