//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUpdateMasterModel
    {
        public int ProductUpdateMasterId { get; set; }
        public string ProductUpdateMasterCode { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public string CreateAccount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatedEmployeeId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedAccount { get; set; }
        public Nullable<int> DeletedEmployeeId { get; set; }
        public string Note { get; set; }
        public bool CreatedIEOther { get; set; }
        public bool Actived { get; set; }
    }
}
