//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountModel
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> RolesId { get; set; }
        public Nullable<bool> isCustomer { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<bool> Actived { get; set; }
    
        public virtual CustomerModel CustomerModel { get; set; }
        public virtual EmployeeModel EmployeeModel { get; set; }
        public virtual RolesModel RolesModel { get; set; }
    }
}
