//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalendarModel()
        {
            this.DiscountModel = new HashSet<DiscountModel>();
        }
    
        public int CalendarId { get; set; }
        public int CourseId { get; set; }
        public string Name { get; set; }
        public int LocationId { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Time { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int NumberOfTrainees { get; set; }
        public Nullable<int> TotalOfReg { get; set; }
        public bool isHot { get; set; }
        public Nullable<int> HotIndex { get; set; }
        public bool Actived { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual CourseModel CourseModel { get; set; }
        public virtual LocationModel LocationModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountModel> DiscountModel { get; set; }
    }
}
