//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_ChicCut_Pre_OrderDetailModel
    {
        public int PreOrderDetailId { get; set; }
        public Nullable<int> PreOrderId { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
        public Nullable<decimal> COGS { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> UnitCOGS { get; set; }
        public Nullable<decimal> MinUnitPrice { get; set; }
        public Nullable<decimal> MaxUnitPrice { get; set; }
    
        public virtual Daily_ChicCut_Pre_OrderModel Daily_ChicCut_Pre_OrderModel { get; set; }
    }
}
