//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountModel
    {
        public int DiscountId { get; set; }
        public int CalendarId { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> Curent { get; set; }
    
        public virtual CalendarModel CalendarModel { get; set; }
    }
}
