//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationOfProductModel
    {
        public int LocationOfProductId { get; set; }
        public string LocationOfProductName { get; set; }
        public string Detail { get; set; }
        public bool Actived { get; set; }
    }
}
