//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDetailModel
    {
        public int PlanDetailId { get; set; }
        public Nullable<int> PlanMasterId { get; set; }
        public Nullable<System.TimeSpan> TimeFrame { get; set; }
        public Nullable<int> AmountOfCus { get; set; }
    }
}
