//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreOrderMasterModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreOrderMasterModel()
        {
            this.PreOrderDetailModel = new HashSet<PreOrderDetailModel>();
        }
    
        public int PreOrderId { get; set; }
        public string PreOrderCode { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> BillDiscountTypeId { get; set; }
        public Nullable<decimal> BillDiscount { get; set; }
        public Nullable<int> BillVAT { get; set; }
        public string SaleName { get; set; }
        public Nullable<System.DateTime> DebtDueDate { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> MoneyTransfer { get; set; }
        public string CompanyName { get; set; }
        public string TaxBillCode { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> TaxBillDate { get; set; }
        public int CustomerId { get; set; }
        public string FullName { get; set; }
        public string IdentityCard { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedAccount { get; set; }
        public Nullable<int> CreatedEmployeeId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedAccount { get; set; }
        public Nullable<int> LastModifiedEmployeeId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedAccount { get; set; }
        public Nullable<int> DeletedEmployeeId { get; set; }
        public bool Actived { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> CustomerLevelId { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<decimal> RemainingAmountAccrued { get; set; }
        public string StatusCode { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> SumCOGSOfOrderDetail { get; set; }
        public Nullable<decimal> SumPriceOfOrderDetail { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TotalVAT { get; set; }
    
        public virtual CustomerModel CustomerModel { get; set; }
        public virtual DiscountTypeModel DiscountTypeModel { get; set; }
        public virtual DistrictModel DistrictModel { get; set; }
        public virtual OrderStatusModel OrderStatusModel { get; set; }
        public virtual PaymentMethodModel PaymentMethodModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreOrderDetailModel> PreOrderDetailModel { get; set; }
        public virtual ProvinceModel ProvinceModel { get; set; }
        public virtual WarehouseModel WarehouseModel { get; set; }
    }
}
