//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAlertModel
    {
        public int ProductId { get; set; }
        public int WarehouseId { get; set; }
        public int RolesId { get; set; }
        public Nullable<decimal> QtyAlert { get; set; }
    
        public virtual ProductModel ProductModel { get; set; }
        public virtual RolesModel RolesModel { get; set; }
        public virtual WarehouseModel WarehouseModel { get; set; }
    }
}
