//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPriceModel
    {
        public int ProductPriceID { get; set; }
        public int CustomerLevelId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual CustomerLevelModel CustomerLevelModel { get; set; }
        public virtual ProductModel ProductModel { get; set; }
    }
}
