//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUpdateDetailModel
    {
        public int ProductUpdateDetailId { get; set; }
        public int ProductUpdateMasterId { get; set; }
        public int ProductId { get; set; }
        public string ProductStoreCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> ImportPrice { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public bool Actived { get; set; }
    }
}
