//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryModel
    {
        public int RegistryId { get; set; }
        public int CourseId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string BirthDay { get; set; }
        public string Phone { get; set; }
        public string Note { get; set; }
        public Nullable<int> CalendarId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> DiscountId { get; set; }
        public Nullable<bool> Actived { get; set; }
    
        public virtual CourseModel CourseModel { get; set; }
    }
}
